enableElasticMaster: true
enableElasticData: true
enableElasticExporter: true

elastic-master:
  nodeGroup: "master"
  replicas: 1
  minimumMasterNodes: -1
  antiAffinity: "soft"
  roles:
    master: "true"
    ingest: "false"
    data: "false"
    remote_cluster_client: "false"
    ml: "false"
  resources:
    requests:
      cpu: "1000m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

elastic-data:
  nodeGroup: "data"
  masterService: "elasticsearch-master"
  replicas: 3
  antiAffinity: "soft"
  roles:
    master: "false"
    ingest: "true"
    data: "true"
    remote_cluster_client: "true"
    ml: "true"
  resources:
    requests:
      cpu: "1000m"
      memory: "768Mi"
    limits:
      cpu: "1000m"
      memory: "768Mi"

prometheus-elasticsearch-exporter:
  serviceMonitor: 
    enabled: true
  es:
    uri: http://elasticsearch-master.{{ .Release.Namespace }}:9200
    timeout: 120s

rabbitmq:
  metrics:
    ## @param metrics.enabled Enable exposing RabbitMQ metrics to be gathered by Prometheus
    ##
    enabled: true
    ## @param metrics.plugins Plugins to enable Prometheus metrics in RabbitMQ
    ##
    plugins: "rabbitmq_prometheus"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.service.ports.metrics }}"
    serviceMonitor:
      enabled: true


mariadb:
  auth:
    rootPassword: f1a9qqwhIJ
    replicationPassword: f1a9qqwhIJ
  # The architecture can be `standalone` or `replication`, in this case, we'll use replication since we need 2 replicas.
  architecture: replication
  primary:
    # Limit the computer resources that the primary will get
    resources:
      requests:
        cpu: "300m"
        memory: "256Mi"
      limits:
        cpu: "700m"
        memory: "256Mi"
  secondary:  
    # Define the amount of replicas we'll have
    replicaCount: 2

    # Limit the computer resources that the secondary will get
    resources:
      requests:
        cpu: "300m"
        memory: "512Mi"
      limits:
        cpu: "700m"
        memory: "512Mi"
  metrics: 
    enabled: true

    # The service monitor enables us to work with prometheus
    serviceMonitor: 
      enabled: true
