apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: brayanmq/api
          env:
            - name: MARIADBENDPOINT
              value: databases-mariadb-primary
            - name: ELASTICINDEX
              value: "jobs"
            - name: MARIADB_USER
              value: "root"
            - name: MARIADBPASS
              valueFrom:
                secretKeyRef:
                  name: databases-mariadb
                  key: mariadb-root-password
                  optional: false
            - name: MARIADBPORT
              value: "3306"
            - name: MARIADB_DB
              value: "workload"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5000
