apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jatsxml
  labels:
    app: app-jatsxml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-jatsxml
  template:
    metadata:
      labels:
        app: app-jatsxml
    spec:
      containers:
        - name: app-jatsxml
          image: achoy08/app-jatsxml
          env:
            - name: HOSTNAME
              value: "app-jatsxml"
            - name: API_URL
              value: "https://api.biorxiv.org/covid19/0"
            - name: RABBITMQ
              value: "databases-rabbitmq"
            - name: OUT_QUEUE
              value: "Final"
            - name: IN_QUEUE
              value: "jatsxml"
            - name: RABBIT_USER
              value: "user"
            - name: RABBITMQPASS
              valueFrom:
                secretKeyRef:
                  name: databases-rabbitmq
                  key: rabbitmq-password
                  optional: false
            - name: MARIADBENDPOINT
              value: databases-mariadb-primary
            - name: MARIADBPASS
              valueFrom:
                secretKeyRef:
                  name: databases-mariadb
                  key: mariadb-root-password
                  optional: false
            - name: MARIADBPORT
              value: "3306"
            - name: MARIADB_USER
              value: "root"
            - name: MARIADB_DB
              value: "workload"
            - name: ELASTICENDPOINT
              value: "elasticsearch-master"

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"