enableMariaDB: true
enableElasticMaster: true
enableElasticData: true
enableElasticExporter: true
enableKibana: true
enableRabbitmq: true

mariadb:
  # The architecture can be `standalone` or `replication`, in this case, we'll use replication since we need 2 replicas.
  architecture: replication
  primary:
    # Limit the computer resources that the primary will get
    resources:
      requests:
        cpu: "300m"
        memory: "256Mi"
      limits:
        cpu: "700m"
        memory: "256Mi"
  secondary:  
    # Define the amount of replicas we'll have
    replicaCount: 2

    # Limit the computer resources that the secondary will get
    resources:
      requests:
        cpu: "300m"
        memory: "512Mi"
      limits:
        cpu: "700m"
        memory: "512Mi"
  metrics: 
    enabled: true

    # The service monitor enables us to work with prometheus
    serviceMonitor: 
      enabled: true
  